### ISSUE TITLE
development tracker

### ISSUE THREAD

**Issue by iaacornus** [trytomakeyouprivate/Fedora-OSTree-Setup#2]
so no one will repeat whats being worked on by who and else.

I will take on, refer [here](https://github.com/trytomakeyouprivate/Fedora-OSTree-Setup/blob/main/ToDo.md):

2, 3, 4, 8, 10

And:

- laptop or pc (to decide whether to proceed for laptop-only optimizations)
- ask what applications to install
- remove flatpak repo and replace applications from fedora repo with from flathub

**Comment by iaacornus** [comment]
Re:

- [ ] Desktop environment/spin -based optimizations (2)
- [ ] Setup of flathub
- [ ] Installation of some flatpak applications
- [ ] Setup of RPMFusion repo
- [ ] Installation of some RPM packages
- [ ] Laptop or PC optimizations
- [ ] Removing fedora repo and replace apps from fedora with from flathub

**Comment by iaacornus** [comment]
the development takes here and is being written in python >= 3.11 @trytomakeyouprivate https://github.com/iaacornus/Fedora-OSTree-Setup/tree/devel
